### ISSUE TITLE
X dim ValueError in annual mean plot

### ISSUE THREAD

**Issue by AnnaKwa** [ai2cm/ace#311]
I ran into an error in a training job (using image [96e824a](https://beaker.org/im/01HSCC0A3CCERNKNJKA5YTRSAD)) where it complained about the x dimension while doing something with an annual mean line plot.  
[Full logs](https://beaker.org/api/v3/jobs/01HSCFHMT7ZVDE26343R7PN7A1/logs?tail=2)
Relevant traceback:
```
2024-03-19T23:49:31.029814944Z Traceback (most recent call last):
2024-03-19T23:49:31.030154111Z   File "/full-model/fme/fme/fcn_training/train.py", line 473, in <module>
2024-03-19T23:49:31.030166121Z     main(yaml_config=args.yaml_config)
2024-03-19T23:49:31.030238020Z   File "/full-model/fme/fme/fcn_training/train.py", line 464, in main
2024-03-19T23:49:31.030245940Z     trainer.train()
2024-03-19T23:49:31.030316410Z   File "/full-model/fme/fme/fcn_training/train.py", line 199, in train
2024-03-19T23:49:31.030321990Z     inference_logs = self.inference_one_epoch()
2024-03-19T23:49:31.030399919Z   File "/full-model/fme/fme/fcn_training/train.py", line 364, in inference_one_epoch
2024-03-19T23:49:31.030405049Z     logs = aggregator.get_logs(label="inference")
2024-03-19T23:49:31.030477248Z   File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
2024-03-19T23:49:31.030482488Z     return func(*args, **kwargs)
2024-03-19T23:49:31.030558357Z   File "/full-model/fme/fme/core/aggregator/inference/main.py", line 161, in get_logs
2024-03-19T23:49:31.030563317Z     logs.update(self._annual.get_logs(label="annual_weighted_mean"))
2024-03-19T23:49:31.030632327Z   File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
2024-03-19T23:49:31.030637297Z     return func(*args, **kwargs)
2024-03-19T23:49:31.030708756Z   File "/full-model/fme/fme/core/aggregator/inference/annual.py", line 179, in get_logs
2024-03-19T23:49:31.030713566Z     gen[name].isel(sample=i_sample).plot(
2024-03-19T23:49:31.030776045Z   File "/opt/conda/lib/python3.8/site-packages/xarray/plot/accessor.py", line 46, in __call__
2024-03-19T23:49:31.030780855Z     return dataarray_plot.plot(self._da, **kwargs)
2024-03-19T23:49:31.030840035Z   File "/opt/conda/lib/python3.8/site-packages/xarray/plot/dataarray_plot.py", line 312, in plot
2024-03-19T23:49:31.030844765Z     return plotfunc(darray, **kwargs)
2024-03-19T23:49:31.030901404Z   File "/opt/conda/lib/python3.8/site-packages/xarray/plot/dataarray_plot.py", line 506, in line
2024-03-19T23:49:31.030906134Z     xplt, yplt, hueplt, hue_label = _infer_line_data(darray, x, y, hue)
2024-03-19T23:49:31.030967894Z   File "/opt/conda/lib/python3.8/site-packages/xarray/plot/dataarray_plot.py", line 76, in _infer_line_data
2024-03-19T23:49:31.030972704Z     _assert_valid_xy(darray, x, "x")
2024-03-19T23:49:31.031026373Z   File "/opt/conda/lib/python3.8/site-packages/xarray/plot/utils.py", line 450, in _assert_valid_xy
2024-03-19T23:49:31.031053123Z     raise ValueError(
2024-03-19T23:49:31.031096983Z ValueError: x must be one of None, 'time'. Received 'year' instead.
```

**Comment by AnnaKwa** [comment]
Update: still present for the current image ([b908e73](https://github.com/ai2cm/full-model/commit/b908e7377d5b881189e4c299b405840a64b5e5b1). I thought maybe it was fixed by some subsequent PR since my test run with this image didn't raise the error, but then my experiment ran into this in the first inline inference. I think maybe my test case was < 1 yr and just skipped the annual mean plots.

**Comment by mcgibbon** [comment]
The exception itself should be resolved by ai2cm/full-model#647 , though it may not plot the annual data when whatever is causing this happens. The exception implies the time dimension of the data is called "time", meaning something went wrong with the year groupby/mean.

I tried to reproduce this in a test but it didn't happen.

**Comment by brianhenn** [comment]
Seconding @AnnaKwa 's post that training with 5y inline inference failed with this error on b908e737. Will try again now that the potential fix has been merged, and see what happens.

**Comment by brianhenn** [comment]
Running on a commit past ai2cm/full-model#647 does appear to resolve it, so that's good! For example: https://wandb.ai/ai2cm/fourcastnet/runs/ovqv7she

A different thing that I am noticing is that inference appears to be quite a bit slower compared when I did some runs on last week on 318f06f. eg, 5y inline timing on current runs below; some of this appears to be due to a non-optimal data loading/forward steps configuration, but the writers/aggs are a big part:

``
335 2024-03-24 17:46:25,428 - root - INFO - data_loading duration: 1071.94s
336 2024-03-24 17:46:25,428 - root - INFO - run_on_batch duration: 844.89s
337 2024-03-24 17:46:25,429 - root - INFO - writer_and_aggregator duration: 2741.29s
``

**Comment by mcgibbon** [comment]
There's a good chance this is the time-dependent aggregators, which I haven't optimized in the same way as the writer (with the hope that it was np.add_at, and that xarray would do it faster). I'll put fixing this (or at least, timing a run with and without these aggregators) on my TODOs.

**Comment by brianhenn** [comment]
I think this was fixed by ai2cm/full-model#647 . If it resurfaces we can reopen.

**Comment by mcgibbon** [comment]
This is still somehow an issue. Reopening. ai2cm/full-model#697 will prevent this from crashing jobs but there's still a problem going on.

This [beaker job](https://beaker.org/ex/01HT32R5865WKADTD0GQ9YP432) which ran with [this version of annual.py](https://github.com/ai2cm/full-model/blob/a201b81e2966469a7cd2959bc922cff695842efa/fme/fme/core/aggregator/inference/annual.py) failed despite the extensive `if "year" in <dataset>.dims:` checks.

**Comment by AnnaKwa** [comment]
I don't yet have the root cause of the bug, but it's only triggered by running on >1 GPU, which explains why I had so much trouble reproducing it in my (1 GPU) interactive session.

I based the debugging runs off of [this experiment](https://beaker.org/ex/01HT0CPMENEF1R9APJSNN08RPF/tasks/01HT0CPMGP1VWXQH8PHRE6XT19/job/01HT0VN6SHDTYQBV5A77WWSN57) ([wandb report](https://wandb.ai/ai2cm/fourcastnet-normalization-sensitivity/runs/elm1nd8f) with empty annual mean plots).

[2024-04-11-repro-annual-mean-bug](https://beaker.org/ex/01HV79S6R7YS37V2Y9ZPF32VKF)) beaker experiment that used the same datasets and copied the inline inference config (with reduced model capacity and training set size) did produce [annual mean plots](https://wandb.ai/ai2cm/ace-debugging/runs/7586n3qz) for inline inference.

[2024-04-11-repro-annual-mean-bug-2gpu](https://beaker.org/ex/01HV7C976ZX7RKXVQX6270PEME) beaker experiment was identical to the previous, but used 2 GPUs.[ Annual mean plots in wandb are empty.](https://wandb.ai/ai2cm/ace-debugging/runs/9mci7ew3)

**Comment by AnnaKwa** [comment]
The fix is simply to change the dim name 'time' to 'year' in this code that gathers datasets: https://github.com/ai2cm/full-model/blob/2e6600c15034b9728bd4f4df7b0569c2e562b13d/fme/fme/core/aggregator/inference/annual.py#L271

However, now my interactive jobs using 2 GPUs hang with 100% gpu utilization during the gather.

**Comment by AnnaKwa** [comment]
[here's](https://beaker.org/ex/01HV7W9KF6DDDECYVNPD3ET87T/tasks/01HV7W9KFEFA9MW00B4NYPZ751/job/01HV7W9PC2A617Y853V2RBDHZ3) an example of a 2 gpu job that hangs on inference when using an image from my branch that fixes the dim name bug and is based of the current main. When running on 2 GPUs with the same changes, but based off earlier main commit d350bc, the job completes with nonempty annual mean plots generated from inline inference.
Based off the debugging statements the job is hanging at the commented line below:

```
    @torch.no_grad()
    def get_logs(self, label: str) -> Dict[str, Any]:
        t0=time.time()
        gathered = self._get_gathered_means()
        logger.debug(f"{time.time()-t0} s to gather means").
            return {}
        target, gen = gathered   ####### hangs here
        logger.debug('target, gen defined')       
```

**Comment by oliverwm1** [comment]
@AnnaKwa this is resolved now right? Feel free to close if so.
